### ISSUE TITLE
Glitched textures for some players.

### ISSUE THREAD

**Issue by Athesiel** [Ancientkingg/fancyPants#3]
I'm still trying to reproduce this, but some of my players are reporting the armour textures glitching out. For one of them, they were working fine, and then today stopped working properly. They're working fine for me, so I have no idea how to even start looking into what could be going wrong. For reference, here's my POV vs my player's POV.

Glitched:
![glitched](https://user-images.githubusercontent.com/47618640/150885149-93b5010e-9e30-45d1-ad8c-bc9b294eb4cb.png)

Intended:
![intended](https://user-images.githubusercontent.com/47618640/150885152-67c65f83-afb2-45ab-be3d-8332c02b8a87.png)

Any idea what could be going wrong? We tried having them delete the resource pack from server-resource-packs, and rejoining, but that did nothing, & we're both using the same resourcepack file, which doesn't edit the shader at all.

**Comment by TehAwesomestKitteh** [comment]
1. Update the shaders to these ones since they provide a lot of fixes: #1 
2. Find out if there's anything different on your end with your players' end. Whatever it may be (Optifine, other resource packs, Minecraft Version, etc.)

**Comment by LoneDev6** [comment]
> 1. Update the shaders to these ones since they provide a lot of fixes: [Various fixes #1](https://github.com/Ancientkingg/fancyPants/pull/1)
> 
>     2. Find out if there's anything different on your end with your players' end. Whatever it may be (Optifine, other resource packs, Minecraft Version, etc.)

https://itemsadder.devs.beer/faq/armors-textures-bugged
