### ISSUE TITLE
Sampler1

### ISSUE THREAD

**Issue by Cboxhero** [Ancientkingg/fancyPants#5]
When loading a resource pack with this shader included, you get this warning in the client console:
"Shader rendertype_armor_cutout_no_cull could not find sampler named Sampler1 in the specified shader program."

Looking through it seems that a Sampler2D with that name doesn't exist anywhere. Only Sampler0 and Sampler2 exist.
This does not stop the shader from working but increases load time quite a bit.

**Comment by Ancientkingg** [comment]
This has been solved by submitting a pull request from the author of the issue. Thank you
