### ISSUE TITLE
Glitched Optifine Donor Cape

### ISSUE THREAD

**Issue by PabloGirol** [Ancientkingg/fancyPants#8]
Some players are noticing a rendering bug on the optifine capes while using elytra and using these shaders...

Glitched texture:
![imagen](https://user-images.githubusercontent.com/47150336/210188963-e1bc7687-aa53-4dbe-bbdf-314e42f38146.png)

Actual cape render:
![imagen](https://user-images.githubusercontent.com/47150336/210188971-6bbf078c-575e-4f88-b697-75581f3f4408.png)

**Comment by Ancientkingg** [comment]
I don't officially support optifine, since it gives too many compatibility problems. Sorry ¯\_(ツ)_/¯
